# -*- coding: utf-8 -*-
"""PythonTask2-ExpenseTracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKKdPdwWpzaRbRuAw7_D5J4UXvDFRSsV
"""

# ==========================================
#        💰 EXPENSE TRACKER 💰
# ==========================================

print("=" * 50)
print("         💰 EXPENSE TRACKER 💰")
print("=" * 50)

expenses = []
total = 0

while True:
    amount = input("\nEnter expense amount (or type 'done' to finish): ₹ ")

    if amount.lower() == "done":
        break

    try:
        amount = float(amount)

        if amount < 0:
            print("❌ Expense cannot be negative!")
            continue

        expenses.append(amount)
        total += amount

        print(f"✅ ₹{amount:.2f} added successfully!")

    except ValueError:
        print("⚠ Please enter a valid number!")

print("\n" + "=" * 50)
print("              📋 EXPENSE SUMMARY")
print("=" * 50)

if len(expenses) == 0:
    print("No expenses entered.")
else:
    for i, expense in enumerate(expenses, start=1):
        print(f"{i}. ₹{expense:.2f}")

    print("-" * 50)
    print(f"🧾 Total Expenses : {len(expenses)}")
    print(f"💵 Total Spent    : ₹{total:.2f}")
    print(f"📊 Average Expense: ₹{total/len(expenses):.2f}")
    print("=" * 50)

print("\n🎉 Thank you for using Expense Tracker!")